# Generated by Django 6.0 on 2025-12-18 14:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=300, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
            ],
            options={
                'verbose_name': 'Galeri Kategorisi',
                'verbose_name_plural': 'Galeri Kategorileri',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(choices=[('fas fa-link', 'Genel Link'), ('fab fa-instagram', 'Instagram'), ('fab fa-facebook', 'Facebook'), ('fab fa-twitter', 'Twitter/X'), ('fab fa-youtube', 'YouTube'), ('fab fa-whatsapp', 'WhatsApp'), ('fas fa-globe', 'Web Sitesi'), ('fas fa-newspaper', 'Haber'), ('fas fa-file-pdf', 'PDF'), ('fas fa-hand-holding-heart', 'Bağış'), ('fas fa-users', 'Gönüllü')], default='fas fa-link', max_length=50, verbose_name='İkon')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Bağlantı',
                'verbose_name_plural': 'Bağlantılar',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL Slug')),
                ('summary', models.TextField(max_length=500, verbose_name='Özet')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Kapak Görseli')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Haber',
                'verbose_name_plural': 'Haberler',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Umut Vagonu', max_length=200, verbose_name='Site Başlığı')),
                ('slogan', models.CharField(default='Geleceğe Umut Taşıyoruz', max_length=300, verbose_name='Slogan')),
                ('about_text', models.TextField(blank=True, default='Umut Vagonu Derneği, ihtiyaç sahiplerine ulaşmak, yüzlerde bir tebessüm oluşturmak için durmaksızın çalışan bir sivil toplum kuruluşudur.', verbose_name='Hakkımızda Metni')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('contact_address', models.TextField(blank=True, verbose_name='Adres')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Banka Adı')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Hesap No')),
                ('bank_iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('stat_lives_touched', models.IntegerField(default=10000, verbose_name='Ulaşılan Hayat')),
                ('stat_projects', models.IntegerField(default=100, verbose_name='Tamamlanan Proje')),
                ('stat_volunteers', models.IntegerField(default=1000, verbose_name='Gönüllü Sayısı')),
                ('stat_cities', models.IntegerField(default=81, verbose_name='Hizmet Verilen İl')),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL Slug')),
                ('bio', models.TextField(blank=True, verbose_name='Biyografi')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='writers/', verbose_name='Fotoğraf')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('order', models.IntegerField(default=0, verbose_name='Sıralama')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'verbose_name': 'Yazar',
                'verbose_name_plural': 'Yazarlar',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Görsel')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Yükleme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landing.gallerycategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Galeri Görseli',
                'verbose_name_plural': 'Galeri Görselleri',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Başlık')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='URL Slug')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/', verbose_name='Görsel')),
                ('is_published', models.BooleanField(default=True, verbose_name='Yayında')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yayın Tarihi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='landing.writer', verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Yazı',
                'verbose_name_plural': 'Yazılar',
                'ordering': ['-published_date'],
            },
        ),
    ]
