# Generated by Django 6.0 on 2025-12-20 11:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_date'], 'verbose_name': 'Köşe Yazısı', 'verbose_name_plural': 'Köşe Yazıları'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(help_text='Yazının tam metni. Paragraflar arasında boş satır bırakın.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Opsiyonel kapak görseli.', null=True, upload_to='articles/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='İşaretlenmezse yazı sitede görünmez.', verbose_name='Yayında'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, help_text='Otomatik oluşturulur.', max_length=300, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(help_text='Yazının başlığı.', max_length=300, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(help_text='Bu yazıyı yazan kişi.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='landing.writer', verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mesaj incelendi mi?', verbose_name='Okundu'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='description',
            field=models.TextField(blank=True, help_text='Kategori hakkında kısa açıklama (opsiyonel).', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='name',
            field=models.CharField(help_text='Örn: Eğitim Projeleri, Yardım Dağıtımları, Etkinlikler...', max_length=200, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='order',
            field=models.IntegerField(default=0, help_text='Küçük sayı önce görünür.', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='slug',
            field=models.SlugField(blank=True, help_text='Otomatik oluşturulur.', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.ForeignKey(help_text='Bu görsel hangi kategoriye ait?', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landing.gallerycategory', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, help_text='Görsel hakkında detaylı bilgi (opsiyonel).', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(help_text='JPG veya PNG formatında. Önerilen max boyut: 2MB.', upload_to='gallery/', verbose_name='Görsel'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Ana sayfada görünsün mü?', verbose_name='Öne Çıkan'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='title',
            field=models.CharField(help_text='Görseli tanımlayan kısa başlık.', max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='link',
            name='description',
            field=models.TextField(blank=True, help_text='Bağlantı hakkında kısa açıklama (opsiyonel).', verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='link',
            name='icon',
            field=models.CharField(choices=[('fas fa-link', '🔗 Genel Link'), ('fab fa-instagram', '📷 Instagram'), ('fab fa-facebook', '📘 Facebook'), ('fab fa-twitter', '🐦 Twitter/X'), ('fab fa-youtube', '📺 YouTube'), ('fab fa-whatsapp', '💬 WhatsApp'), ('fas fa-globe', '🌐 Web Sitesi'), ('fas fa-newspaper', '📰 Haber'), ('fas fa-file-pdf', '📄 PDF'), ('fas fa-hand-holding-heart', '❤️ Bağış'), ('fas fa-users', '👥 Gönüllü'), ('fas fa-envelope', '📧 E-posta'), ('fas fa-phone', '📞 Telefon')], default='fas fa-link', help_text='Bağlantı yanında gösterilecek simge.', max_length=50, verbose_name='İkon'),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pasif bağlantılar sitede görünmez.', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='link',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Ana sayfada 'Hızlı Erişim' bölümünde görünsün mü?", verbose_name='Öne Çıkan'),
        ),
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.IntegerField(default=0, help_text='Küçük sayı önce görünür.', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='link',
            name='title',
            field=models.CharField(help_text='Bağlantının görünen adı.', max_length=200, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.URLField(help_text='Tam web adresi. Örn: https://instagram.com/kullanici', verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(help_text='Haberin tam metni. Paragraflar arasında boş satır bırakın.', verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, help_text='Önerilen boyut: 1200x630 piksel (16:9 oran).', null=True, upload_to='news/', verbose_name='Kapak Görseli'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='İşaretlenirse haber ana sayfada büyük olarak gösterilir.', verbose_name='Öne Çıkan'),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_published',
            field=models.BooleanField(default=True, help_text='İşaretlenmezse haber sitede görünmez (Taslak).', verbose_name='Yayında'),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Haber bu tarihten itibaren görünür olur.', verbose_name='Yayın Tarihi'),
        ),
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.SlugField(blank=True, help_text='Otomatik oluşturulur. Haberin web adresinde görünür (örn: /haberler/haber-basligi)', max_length=300, unique=True, verbose_name='URL Slug'),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.TextField(help_text='Haber listelerinde görünen kısa açıklama. 2-3 cümle yeterli.', max_length=500, verbose_name='Özet'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(help_text='Haberin başlığı. Kısa ve etkileyici olmalı.', max_length=300, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='about_text',
            field=models.TextField(blank=True, default='Umut Vagonu Derneği, ihtiyaç sahiplerine ulaşmak, yüzlerde bir tebessüm oluşturmak için durmaksızın çalışan bir sivil toplum kuruluşudur.', help_text='Footer ve meta açıklamalarında kullanılır.', verbose_name='Hakkımızda Metni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bank_account',
            field=models.CharField(blank=True, help_text='Banka hesap numarası.', max_length=100, verbose_name='Hesap No'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bank_iban',
            field=models.CharField(blank=True, help_text='TR ile başlayan IBAN numarası.', max_length=50, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Örn: Ziraat Bankası', max_length=100, verbose_name='Banka Adı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_address',
            field=models.TextField(blank=True, help_text='Dernek merkez adresi.', verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Örn: bilgi@umutvagonu.org', max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Örn: 0555 123 45 67', max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.URLField(blank=True, help_text="Facebook sayfa URL'si.", verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.URLField(blank=True, help_text="Instagram profil URL'si. Örn: https://instagram.com/umutvagonumanisa", verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_title',
            field=models.CharField(default='Umut Vagonu', help_text='Tarayıcı sekmesinde ve logoda görünecek başlık.', max_length=200, verbose_name='Site Başlığı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='slogan',
            field=models.CharField(default='Geleceğe Umut Taşıyoruz', help_text='Logo altında ve sayfa başlıklarında görünür.', max_length=300, verbose_name='Slogan'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_cities',
            field=models.IntegerField(default=81, help_text="Ana sayfada gösterilen 'Hizmet Verilen İl' sayısı.", verbose_name='Hizmet Verilen İl'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_lives_touched',
            field=models.IntegerField(default=10000, help_text="Ana sayfada gösterilen 'Ulaşılan Hayat' sayısı.", verbose_name='Ulaşılan Hayat'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_projects',
            field=models.IntegerField(default=100, help_text="Ana sayfada gösterilen 'Tamamlanan Proje' sayısı.", verbose_name='Tamamlanan Proje'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='stat_volunteers',
            field=models.IntegerField(default=1000, help_text="Ana sayfada gösterilen 'Gönüllü Ordusu' sayısı.", verbose_name='Gönüllü Sayısı'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, help_text="Twitter profil URL'si.", verbose_name='Twitter/X'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='youtube_url',
            field=models.URLField(blank=True, help_text="YouTube kanal URL'si.", verbose_name='YouTube'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='bio',
            field=models.TextField(blank=True, help_text='Yazarın kısa özgeçmişi. Yazar profil sayfasında görünür.', verbose_name='Biyografi'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='email',
            field=models.EmailField(blank=True, help_text='Opsiyonel. Okuyucuların yazara ulaşması için.', max_length=254, verbose_name='E-posta'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Pasif yazarlar listede görünmez.', verbose_name='Aktif'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='name',
            field=models.CharField(help_text='Yazarın tam adı.', max_length=200, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='order',
            field=models.IntegerField(default=0, help_text='Küçük sayı önce görünür. Örn: 1, 2, 3...', verbose_name='Sıralama'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profil fotoğrafı. Kare formatta (1:1 oran) önerilir.', null=True, upload_to='writers/', verbose_name='Fotoğraf'),
        ),
        migrations.AlterField(
            model_name='writer',
            name='slug',
            field=models.SlugField(blank=True, help_text='Otomatik oluşturulur.', max_length=200, unique=True, verbose_name='URL Slug'),
        ),
    ]
