# Generated by Django 6.0 on 2025-12-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_article_options_alter_article_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Yazılımcı tarafından belirlenen benzersiz kod. Örn: 'nav_home', 'footer_about_title'. DEĞİŞTİRMEYİNİZ!", max_length=200, unique=True, verbose_name='İçerik Anahtarı')),
                ('content_text', models.TextField(help_text='Görünecek metin veya HTML kodu.', verbose_name='İçerik')),
                ('description', models.CharField(help_text='Bu içeriğin nerede kullanıldığını hatırlatmak için kısa not.', max_length=300, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif yapılırsa varsayılan metin görünür.', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Site İçeriği',
                'verbose_name_plural': 'Site İçerikleri',
                'ordering': ['key'],
            },
        ),
    ]
