# Generated by Django 6.0 on 2025-12-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_sitecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Üyenin tam adı.', max_length=200, verbose_name='Ad Soyad')),
                ('title', models.CharField(help_text='Görevi/Pozisyonu. Örn: Başkan, Genel Sekreter, Sayman.', max_length=200, verbose_name='Unvan')),
                ('photo', models.ImageField(blank=True, help_text='Profil fotoğrafı. Önerilen boyut: 400x400 piksel (kare).', null=True, upload_to='organization/', verbose_name='Fotoğraf')),
                ('bio', models.TextField(blank=True, help_text='Kısa özgeçmiş veya tanıtım metni.', verbose_name='Biyografi')),
                ('role_type', models.IntegerField(choices=[(1, 'Kurucu Üye'), (2, 'Yönetim Kurulu'), (3, 'Denetim Kurulu'), (4, 'Takım Lideri'), (5, 'Gönüllü')], default=5, help_text='Hiyerarşideki pozisyonu. Sayfada gruplama için kullanılır.', verbose_name='Rol Türü')),
                ('order', models.IntegerField(default=0, help_text='Aynı rol grubundaki sıralama. Küçük sayı önce görünür.', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif üyeler sitede görünmez.', verbose_name='Aktif')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter/X')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Organizasyon Üyesi',
                'verbose_name_plural': 'Organizasyon Üyeleri',
                'ordering': ['role_type', 'order', 'name'],
            },
        ),
    ]
