# Generated by Django 6.0 on 2025-12-30 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_organizationmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
            ],
            options={
                'verbose_name': 'Hakkımızda Ayarı',
                'verbose_name_plural': 'Hakkımızda Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='ContactContent',
            fields=[
            ],
            options={
                'verbose_name': 'İletişim Ayarı',
                'verbose_name_plural': 'İletişim Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='FooterContent',
            fields=[
            ],
            options={
                'verbose_name': 'Footer Ayarı',
                'verbose_name_plural': 'Footer Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='NavbarContent',
            fields=[
            ],
            options={
                'verbose_name': 'Navbar Ayarı',
                'verbose_name_plural': 'Navbar Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.ForeignKey(help_text='Bu yazıyı yazan kişi.', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='landing.writer', verbose_name='Yazar'),
        ),
    ]
