# Generated by Django 6.0 on 2025-12-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_aboutcontent_contactcontent_footercontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryContent',
            fields=[
            ],
            options={
                'verbose_name': 'Galeri Sayfası Ayarı',
                'verbose_name_plural': 'Galeri Sayfası Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='HomeContent',
            fields=[
            ],
            options={
                'verbose_name': 'Ana Sayfa Ayarı',
                'verbose_name_plural': 'Ana Sayfa Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='LinkContent',
            fields=[
            ],
            options={
                'verbose_name': 'Bağlantılar Sayfası Ayarı',
                'verbose_name_plural': 'Bağlantılar Sayfası Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
            ],
            options={
                'verbose_name': 'Haber Sayfası Ayarı',
                'verbose_name_plural': 'Haber Sayfası Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='OrgPageContent',
            fields=[
            ],
            options={
                'verbose_name': 'Organizasyon Sayfası Ayarı',
                'verbose_name_plural': 'Organizasyon Sayfası Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='WriterContent',
            fields=[
            ],
            options={
                'verbose_name': 'Yazar Köşesi Ayarı',
                'verbose_name_plural': 'Yazar Köşesi Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
    ]
