# Generated by Django 6.0 on 2025-12-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_gallerycontent_homecontent_linkcontent_newscontent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDashboardContent',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Panel İçerik Ayarı',
                'verbose_name_plural': 'Admin Panel İçerik Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='ArticleDetailContent',
            fields=[
            ],
            options={
                'verbose_name': 'Yazı Detay Sayfası Ayarı',
                'verbose_name_plural': 'Yazı Detay Sayfası Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
        migrations.CreateModel(
            name='ErrorPageContent',
            fields=[
            ],
            options={
                'verbose_name': 'Hata Sayfaları Ayarı',
                'verbose_name_plural': 'Hata Sayfaları Ayarları',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('landing.sitecontent',),
        ),
    ]
