# Generated by Django 6.0 on 2025-12-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_admindashboardcontent_articledetailcontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='developer_name',
            field=models.CharField(default='Furkan Bulut', help_text="Footer'da görünecek geliştirici adı.", max_length=100, verbose_name='Geliştirici Adı'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_url',
            field=models.URLField(default='https://furkanbulut.vercel.app/', help_text='Geliştiricinin web sitesi.', verbose_name='Geliştirici Linki'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Tarayıcı sekmesinde görünen ikon. Önerilen: 32x32 piksel (PNG).', null=True, upload_to='site/', verbose_name='Favicon'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Site logosu. Önerilen boyut: 200x60 piksel (PNG veya SVG).', null=True, upload_to='site/', verbose_name='Logo'),
        ),
    ]
