# Generated by Django 6.0 on 2025-12-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0008_sitesettings_developer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_url',
            field=models.URLField(default='https://umutvagonu.org/', help_text="Linktree sayfasında 'Ana Siteye Git' butonu için kullanılacak adres.", verbose_name='Site Adresi'),
        ),
    ]
