# Generated by Django 5.2.8 on 2026-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_sitesettings_site_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('mission_vision', 'Misyon & Vizyon Kartları'), ('activity', 'Neler Yapıyoruz Kartları')], default='mission_vision', help_text='Kartın nerede görüneceğini belirler.', max_length=20, verbose_name='Kart Türü')),
                ('title', models.CharField(help_text='Kartın başlığı. Örn: Misyonumuz, Vizyonumuz', max_length=200, verbose_name='Başlık')),
                ('content', models.TextField(help_text='Kartın açıklama metni.', verbose_name='İçerik')),
                ('icon', models.CharField(choices=[('fas fa-bullseye', '🎯 Hedef (Misyon)'), ('fas fa-eye', '👁️ Göz (Vizyon)'), ('fas fa-gem', '💎 Değer'), ('fas fa-heart', '❤️ Kalp'), ('fas fa-hand-holding-heart', '🤲 Yardım'), ('fas fa-graduation-cap', '🎓 Eğitim'), ('fas fa-users', '👥 İnsanlar'), ('fas fa-globe', '🌍 Dünya'), ('fas fa-lightbulb', '💡 Ampul'), ('fas fa-star', '⭐ Yıldız'), ('fas fa-seedling', '🌱 Fidan'), ('fas fa-hands-helping', '🤝 Dayanışma'), ('fas fa-book', '📖 Kitap'), ('fas fa-school', '🏫 Okul'), ('fas fa-home', '🏠 Ev'), ('fas fa-gift', '🎁 Hediye')], default='fas fa-star', help_text='Kartın ikonu.', max_length=50, verbose_name='İkon')),
                ('order', models.IntegerField(default=0, help_text='Küçük sayı önce görünür.', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, help_text='Pasif kartlar sitede görünmez.', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Hakkımızda Kartı',
                'verbose_name_plural': 'Hakkımızda Kartları',
                'ordering': ['card_type', 'order'],
            },
        ),
    ]
