"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-rs=7sbuyw0teaiej0imuo7fvj7#a%j!o=hr15y@je_4+w4+!#5')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')



# Application definition

INSTALLED_APPS = [
    # Django Unfold - Modern Admin Theme
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    
    # Cloudinary Media Storage
    'cloudinary_storage',
    'cloudinary',
    
    'landing',
]

# =============================================================================
# DJANGO UNFOLD CONFIGURATION
# =============================================================================
from django.templatetags.static import static
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "Umut Vagonu",
    "SITE_HEADER": "Umut Vagonu Yönetim Paneli",
    "SITE_URL": "/",
    "SITE_SYMBOL": "volunteer_activism",  # Material icon
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    
    # Dashboard callback - istatistik verileri için
    "DASHBOARD_CALLBACK": "landing.utils.dashboard_callback",
    
    # Tema renkleri - Umut Vagonu yeşil teması
    "COLORS": {
        "primary": {
            "50": "#ecfdf5",
            "100": "#d1fae5",
            "200": "#a7f3d0",
            "300": "#6ee7b7",
            "400": "#34d399",
            "500": "#10b981",
            "600": "#059669",
            "700": "#047857",
            "800": "#065f46",
            "900": "#064e3b",
            "950": "#022c22",
        },
    },
    
    # Sidebar Navigation
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Ana Panel",
                "separator": True,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                    {
                        "title": "Siteyi Görüntüle",
                        "icon": "public",
                        "link": "/",
                    },
                ],
            },
            {
                "title": "Site Yönetimi",
                "separator": True,
                "items": [
                    {
                        "title": "Site Ayarları",
                        "icon": "settings",
                        "link": reverse_lazy("admin:landing_sitesettings_changelist"),
                    },
                    {
                        "title": "Ana Sayfa Ayarları",
                        "icon": "home",
                        "link": reverse_lazy("admin:landing_homecontent_changelist"),
                    },
                    {
                        "title": "Hakkımızda Sayfası",
                        "icon": "info",
                        "link": reverse_lazy("admin:landing_aboutcontent_changelist"),
                    },
                    {
                        "title": "Organizasyon Sayfası",
                        "icon": "corporate_fare",
                        "link": reverse_lazy("admin:landing_orgpagecontent_changelist"),
                    },
                    {
                        "title": "Haber Sayfası",
                        "icon": "feed",
                        "link": reverse_lazy("admin:landing_newscontent_changelist"),
                    },
                    {
                        "title": "Haber Detay Sayfası",
                        "icon": "article",
                        "link": reverse_lazy("admin:landing_articledetailcontent_changelist"),
                    },
                    {
                        "title": "Galeri Sayfası",
                        "icon": "collections",
                        "link": reverse_lazy("admin:landing_gallerycontent_changelist"),
                    },
                    {
                        "title": "Yazar Köşesi Ayarları",
                        "icon": "assignment_ind",
                        "link": reverse_lazy("admin:landing_writercontent_changelist"),
                    },
                    {
                        "title": "Bağlantılar Sayfası",
                        "icon": "link",
                        "link": reverse_lazy("admin:landing_linkcontent_changelist"),
                    },
                    {
                        "title": "İletişim Sayfası",
                        "icon": "contact_mail",
                        "link": reverse_lazy("admin:landing_contactcontent_changelist"),
                    },
                    {
                        "title": "Admin Dashboard",
                        "icon": "dashboard_customize",
                        "link": reverse_lazy("admin:landing_admindashboardcontent_changelist"),
                    },
                    {
                        "title": "Navbar Yönetimi",
                        "icon": "menu",
                        "link": reverse_lazy("admin:landing_navbarcontent_changelist"),
                    },
                    {
                        "title": "Footer Yönetimi",
                        "icon": "branding_watermark",
                        "link": reverse_lazy("admin:landing_footercontent_changelist"),
                    },
                    {
                        "title": "Organizasyon Üyeleri",
                        "icon": "groups",
                        "link": reverse_lazy("admin:landing_organizationmember_changelist"),
                    },
                ],
            },

            {
                "title": "İçerik Yönetimi",
                "separator": True,
                "items": [
                    {
                        "title": "Haberler",
                        "icon": "newspaper",
                        "link": reverse_lazy("admin:landing_news_changelist"),
                        "badge": "landing.utils.get_news_count",
                    },
                    {
                        "title": "Yazarlar",
                        "icon": "person",
                        "link": reverse_lazy("admin:landing_writer_changelist"),
                    },
                    {
                        "title": "Köşe Yazıları",
                        "icon": "edit_note",
                        "link": reverse_lazy("admin:landing_article_changelist"),
                    },
                ],
            },
            {
                "title": "Galeri",
                "separator": True,
                "items": [
                    {
                        "title": "Kategoriler",
                        "icon": "folder",
                        "link": reverse_lazy("admin:landing_gallerycategory_changelist"),
                    },
                    {
                        "title": "Görseller",
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:landing_galleryimage_changelist"),
                    },
                ],
            },
            {
                "title": "Diğer",
                "separator": True,
                "items": [
                    {
                        "title": "Bağlantılar",
                        "icon": "link",
                        "link": reverse_lazy("admin:landing_link_changelist"),
                    },
                    {
                        "title": "İletişim Mesajları",
                        "icon": "mail",
                        "link": reverse_lazy("admin:landing_contactmessage_changelist"),
                    },
                ],
            },
            {
                "title": "Kullanıcı Yönetimi",
                "separator": True,
                "items": [
                    {
                        "title": "Kullanıcılar",
                        "icon": "people",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Gruplar",
                        "icon": "groups",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files for Vercel
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'landing.context_processors.site_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Supabase PostgreSQL (from .env)
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME', 'postgres'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.getenv('DB_SSLMODE', 'prefer'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-TR'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# =============================================================================
# CLOUDINARY MEDIA STORAGE
# =============================================================================
# Medya dosyalarını Cloudinary'ye yükle (production için önerilir)
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', ''),
}

# Production'da Cloudinary kullan, development'ta local storage
if not DEBUG:
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# =============================================================================
# WHITENOISE STATIC FILES (for Vercel)
# =============================================================================
# Production'da WhiteNoise kullan
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
